application: stockupdator
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stock_updater
  script: stock_updater.app
  login: admin  
- url: /_ah/mail/.+
  script: handle_email.app
- url: /_ah/queue/default
  script: stock_worker.app
  login: admin  

libraries:
- name: webapp2
  version: latest
  
inbound_services:
- mail
