application: stockupdator
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stock_updater
  script: stock_updater.app
- url: /_ah/mail/.+
  script: handle_email.app
  login: admin  
#- url: /.*
#  script: guestbook.app


libraries:
- name: webapp2
  version: latest
  
inbound_services:
- mail
