application: stockupdator
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stock_updater
  script: stock_updater.app
- url: /.*
  script: guestbook.app


libraries:
- name: webapp2
  version: "2.5.2"
